server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy



# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    dynamic:
      datasource:
        # 主库数据源 - MyBatis Plus
        primary:
          driver-class-name: ${PRIMARY_DB_DRIVER:com.mysql.cj.jdbc.Driver}
          url: jdbc:mysql://${PRIMARY_DB_HOST:117.72.152.117}:${PRIMARY_DB_PORT:13306}/${PRIMARY_DB_NAME:ai-agent-station-study}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          username: ${PRIMARY_DB_USER:root}
          password: ${PRIMARY_DB_PASSWORD:123456}
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            minimum-idle: ${PRIMARY_DB_MIN_IDLE:5}
            maximum-pool-size: ${PRIMARY_DB_MAX_POOL_SIZE:15}
            idle-timeout: ${PRIMARY_DB_IDLE_TIMEOUT:30000}
            pool-name: PrimaryHikariCP
            max-lifetime: ${PRIMARY_DB_MAX_LIFETIME:28740000}
            connection-timeout: ${PRIMARY_DB_CONNECTION_TIMEOUT:30000}
            connection-test-query: SELECT 1
        # readonly数据源 - JDBC
        pgvector:
          url: jdbc:postgresql://${READONLY_DB_HOST:117.72.152.117}:${READONLY_DB_PORT:15432}/${READONLY_DB_NAME:ai-rag-knowledge}
          driver-class-name: ${READONLY_DB_DRIVER:org.postgresql.Driver}
          username: ${READONLY_DB_USERNAME:root}
          password: ${READONLY_DB_PASSWORD:123456}
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            minimum-idle: ${READONLY_DB_MIN_IDLE:5}
            maximum-pool-size: ${READONLY_DB_MAX_POOL_SIZE:15}
            idle-timeout: ${READONLY_DB_IDLE_TIMEOUT:30000}
            pool-name: PgvectorHikariCP
            max-lifetime: ${READONLY_DB_MAX_LIFETIME:28740000}
            connection-timeout: ${READONLY_DB_CONNECTION_TIMEOUT:30000}
            connection-test-query: SELECT 1
  ai:
    openai:
      base-url: https://globalai.vip
      api-key: sk-igZGYZBslPs4UxqU1r8BuprgCFzD388sk36Mwnp95jxsfgKp
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
        endpoint: https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings
        model: text-embedding-v4
        options:
          num_ctx: 512
    agent:
      auto-config:
        enabled: true
        client-ids: 6001,3101,3102,3103,3104

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
# Redis
redis:
  sdk:
    config:
      host: 117.72.152.117
      port: 16379
      pool-size: 10
      password: 123456
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml